const publicFolder = import.meta.env.VITE_PUBLIC_FOLDER;

export const Users = [
  {
    id: 1,
    profilePicture: `${publicFolder}person/1.jpeg`,
    username: "James Kingley",
  },
  {
    id: 2,
    profilePicture: `${publicFolder}person/2.jpeg`,
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: `${publicFolder}person/3.jpeg`,
    username: "Alex Durden",
  },
  {
    id: 4,
    profilePicture: `${publicFolder}person/4.jpeg`,
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: `${publicFolder}person/5.jpeg`,
    username: "Thomas Holden",
  },
  {
    id: 6,
    profilePicture: `${publicFolder}person/6.jpeg`,
    username: "Shirley Beauchamp",
  },
  {
    id: 7,
    profilePicture: `${publicFolder}person/7.jpeg`,
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: `${publicFolder}person/8.jpeg`,
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: `${publicFolder}person/9.jpeg`,
    username: "Gary Duty",
  },
  {
    id: 10,
    profilePicture: `${publicFolder}person/10.jpeg`,
    username: "Sammy Kovac",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: `${publicFolder}post/1.jpeg`,
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: `${publicFolder}post/2.jpeg`,
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: `${publicFolder}post/3.jpeg`,
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: `${publicFolder}post/4.jpeg`,
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: `${publicFolder}post/5.jpeg`,
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: `${publicFolder}post/6.jpeg`,
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: `${publicFolder}post/7.jpeg`,
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: `${publicFolder}post/8.jpeg`,
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: `${publicFolder}post/9.jpeg`,
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: `${publicFolder}post/10.jpeg`,
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
